services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: your-secret-key
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: yourdomain.com,render.com
