services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application
    autoDeploy: true
    envVars:
      - key: SECRET_KEY
        value: Tanbeeh-Dashboard
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: tanbeeh-dashboard-frontend.vercel.app,render.com
