# Generated by Django 5.2.7 on 2025-10-18 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('tr_number', models.CharField(max_length=20, unique=True)),
                ('role', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('its_number', models.CharField(max_length=20)),
                ('class_name', models.CharField(max_length=10)),
                ('hizb', models.CharField(max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
