# Generated by Django 6.0 on 2026-01-08 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_student_attendance__darajah_10d8da_idx'),
        ('login', '0002_customuser_hizb_customuser_is_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='room',
        ),
        migrations.AddField(
            model_name='customuser',
            name='darajah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.darajah'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='attendance.student'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hizb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.hizb'),
        ),
    ]
