# Generated by Django 6.0 on 2026-01-06 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Darajah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Class', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hizb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown Hizb', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('tp', models.TimeField(blank=True, null=True)),
                ('attendance_type', models.CharField(choices=[('fajr', 'Fajr'), ('maghrib_isha', 'Maghrib & Isha'), ('dua', "Du'a")], default='fajr', max_length=20)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], default='present', max_length=20)),
                ('remarks', models.TextField(blank=True, default='', null=True)),
                ('is_temp', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_flags', to=settings.AUTH_USER_MODEL)),
                ('flagged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('attendance_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='attendance.attendancerecord')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('flag', 'Flagged student'), ('unflag', 'Unflagged student'), ('login', 'User login'), ('logout', 'User logout'), ('password_change', 'Password change'), ('data_view', 'Viewed attendance data'), ('user_create', 'Created new user'), ('user_reset_password', 'Admin reset user password')], default='login', max_length=50)),
                ('target', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HizbAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deputy_prefect', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deputy_prefect_hizb', to=settings.AUTH_USER_MODEL)),
                ('hizb', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.hizb')),
                ('prefect', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prefect_hizb', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HizbGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.PositiveIntegerField(default=1)),
                ('hizb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='attendance.hizb')),
            ],
            options={
                'unique_together': {('hizb', 'group_number')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='Notification')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.attendanceflag')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trno', models.CharField(default='0000', max_length=50, unique=True)),
                ('bed_name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('room', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('pantry', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('location', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('darajah', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='attendance.darajah')),
                ('hizb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='attendance.hizb')),
                ('hizb_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='attendance.hizbgroup')),
            ],
        ),
        migrations.CreateModel(
            name='MuaddibGroupAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizb_group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='muaddib_assignments', to='attendance.hizbgroup')),
                ('muaddib', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='muaddib_groups', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='muaddib_students', to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='MasoolAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('darajah', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='masool_assignments', to='attendance.darajah')),
                ('masool', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='masool_assignments', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='masool_students', to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='LajnatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lajnat_member', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lajnat_assignments', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='lajnat_students', to='attendance.student')),
            ],
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.student'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'attendance_type'], name='attendance__date_b6fe94_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status'], name='attendance__status_741eb8_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['-date'], name='attendance__date_b73b54_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'date', 'attendance_type'), name='unique_attendance_record'),
        ),
    ]
