# Generated by Django 6.0 on 2026-01-03 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceflag',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_flags', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_temp',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('flag', 'Flagged student'), ('unflag', 'Unflagged student'), ('login', 'User login'), ('logout', 'User logout'), ('password_change', 'Password change'), ('data_view', 'Viewed attendance data'), ('user_create', 'Created new user'), ('user_reset_password', 'Admin reset user password')], max_length=50)),
                ('target', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HizbAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizb', models.CharField(max_length=50, unique=True)),
                ('deputy_prefect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deputy_prefect_hizb', to=settings.AUTH_USER_MODEL)),
                ('prefect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefect_hizb', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LajnatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lajnat_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lajnat_assignments', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='lajnat_students', to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='MasoolAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masool_assignments', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='masool_students', to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='MuaddibGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hizb', models.CharField(max_length=50)),
                ('muaddib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muaddib_groups', to=settings.AUTH_USER_MODEL)),
                ('students', models.ManyToManyField(related_name='muaddib_students', to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_flag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.attendanceflag')),
            ],
        ),
    ]
