# Generated by Django 6.0 on 2026-01-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['darajah', 'hizb', 'hizb_group'], name='attendance__darajah_10d8da_idx'),
        ),
    ]
