# Generated by Django 6.0 on 2026-01-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendancerecord_attendance__date_b6fe94_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='tp',
            field=models.TimeField(null=True),
        ),
    ]
